# Generated by Django 4.0.5 on 2022-06-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedinApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='linkedin_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='password', max_length=500)),
            ],
        ),
    ]
