# Generated by Django 4.0.5 on 2022-06-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedinApp', '0002_linkedin_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedin_account',
            name='email',
            field=models.EmailField(default='exemple@exemple.com', max_length=254),
        ),
    ]
