# Generated by Django 4.0.5 on 2022-07-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedinApp', '0004_linkedin_profils_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedin_profils',
            name='education',
            field=models.CharField(blank=True, default='NaN', max_length=200),
        ),
        migrations.AddField(
            model_name='linkedin_profils',
            name='geoCountryName',
            field=models.CharField(blank=True, default='NaN', max_length=200),
        ),
        migrations.AddField(
            model_name='linkedin_profils',
            name='geoLocationName',
            field=models.CharField(blank=True, default='NaN', max_length=200),
        ),
    ]
